trigger:
  branches:
    include:
      - main  # Automatically trigger on changes to the 'main' branch
  paths:
    include:
      - 'infrastructure/**'  # Trigger on any changes under the infrastructure folder

pr:
  branches:
    include:
      - main  # Automatically trigger on PRs to the 'main' branch
  paths:
    include:
      - 'infrastructure/**'  # Trigger on any changes under the infrastructure folder

pool:
  name: Default  # Use your self-hosted agent pool name (change if using custom pool)

variables:
  AZURE_RESOURCE_GROUP: 'azure-cloud-resume-rg'  # Set this to your resource group name
  AZURE_TENANT_ID: 'b41db68e-4e43-42ce-9121-a29e1dd53e32'  # Your tenant ID
  AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)  # Set in pipeline variables or key vault
  AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)  # Set in pipeline variables or key vault
  location: 'Australia East'  # Define location here for reusability
  environment: 'dev'  # Define environment type

jobs:
- job: DeployInfrastructure
  displayName: 'Deploy Infrastructure'
  steps:
    
    # Step 1: Login to Azure using Service Principal
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureResumeConnection'  # Replace with your Azure service connection name
        scriptType: 'powershell'  # Use Windows PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Logging in to Azure..."
          az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
          echo "Login successful!"
      displayName: 'Azure Login'
    
    # Step 2: Deploy Bicep file using az deployment group create
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureResumeConnection'  # Replace with your Azure service connection name
        scriptType: 'powershell'  # Use Windows PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Starting deployment..."
          az deployment group create ^
            --resource-group $(AZURE_RESOURCE_GROUP) ^
            --template-file ./infrastructure/main.bicep ^
            --parameters ./infrastructure/parameters.bicepparam
      displayName: 'Deploy Bicep Template'

    # Step 3: Logout from Azure
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureResumeConnection'  # Replace with your Azure service connection name
        scriptType: 'powershell'  # Use Windows PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          az logout
      displayName: 'Azure Logout'
