trigger:
  branches:
    include:
      - main  # Automatically trigger on changes to the 'main' branch
  paths:
    include:
      - 'infrastructure/**'  # Trigger on any changes under the infrastructure folder

pr:
  branches:
    include:
      - main  # Automatically trigger on PRs to the 'main' branch
  paths:
    include:
      - 'infrastructure/**'  # Trigger on any changes under the infrastructure folder

pool:
  name: Default  # Use your self-hosted agent pool name (change if using custom pool)

variables:
  AZURE_RESOURCE_GROUP: 'azure-cloud-resume-rg'  # Set this to your resource group name
  location: 'Australia East'  # Define location here for reusability
  environment: 'dev'  # Define environment type

jobs:
- job: DeployInfrastructure
  displayName: 'Deploy Infrastructure'
  steps:
    
    # Step 1: Deploy Bicep file using az deployment group create
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureResumeConnection'  # Replace with your Azure service connection name
        scriptType: 'powershell'  # Use Windows PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Starting deployment..."
          az deployment group create ^
            --resource-group $(AZURE_RESOURCE_GROUP) ^
            --template-file ./infrastructure/main.bicep ^
            --parameters ./infrastructure/parameters.bicepparam
      displayName: 'Deploy Bicep Template'

    # Step 2: Logout from Azure (Optional, if you want to logout explicitly)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureResumeConnection'  # Replace with your Azure service connection name
        scriptType: 'powershell'  # Use Windows PowerShell
        scriptLocation: 'inlineScript'
        inlineScript: |
          az logout
      displayName: 'Azure Logout'
