trigger:
  branches:
    include:
      - main  # Trigger on changes to the 'main' branch
  paths:
    include:
      - frontend/**  # Trigger on changes under the 'frontend' folder

pr:
  branches:
    include:
      - main  # Trigger on PRs to the 'main' branch
  paths:
    include:
      - frontend/**  # Trigger on changes under the 'frontend' folder

pool:
  name: Default  # Use your self-hosted agent pool name

variables:
  rgname: 'azure-cloud-resume-rg'  # Replace with your resource group name
  location: 'Australia East'  # Define location here for reusability
  STORAGE_ACCOUNT_NAME: 'azureresumewebsitejv'  # Replace with your storage account name
  STORAGE_ACCOUNT_KEY: $(STORAGE_ACCOUNT_KEY)  # Set your Storage Account key here (or through pipeline secrets)
  CDN_PROFILE_NAME: 'jarrodsazureresume'  # Replace with your CDN profile name
  CDN_ENDPOINT_NAME: 'jarrodvecchietsresume'  # Replace with your CDN endpoint name

jobs:
  - job: DeployFrontend
    displayName: 'Deploy Frontend to Azure'
    steps:
      - checkout: self

      # Step 1: Upload files to blob storage
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'AzureResumeConnection'  # Replace with your Azure service connection name
          scriptType: powershell  # Switch back to PowerShell
          scriptLocation: inlineScript
          inlineScript: |
            echo "Uploading files to blob storage..."
            az storage blob upload-batch --account-name $(STORAGE_ACCOUNT_NAME) --account-key $(STORAGE_ACCOUNT_KEY) -d "`$web" -s "$(Build.SourcesDirectory)/frontend" --overwrite
        displayName: 'Upload to Blob Storage'

      # Step 2: Purge the CDN endpoint cache
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'AzureResumeConnection'
          scriptType: powershell  # Switch back to PowerShell
          scriptLocation: inlineScript
          inlineScript: |
            echo "Purging CDN endpoint cache..."
            az cdn endpoint purge --content-paths "/*" --profile-name $(CDN_PROFILE_NAME) --name $(CDN_ENDPOINT_NAME) --resource-group $(rgname)
        displayName: 'Purge CDN Cache'

      # Step 3: Azure Logout
      - task: AzureCLI@2
        displayName: 'Azure Logout'
        inputs:
          azureSubscription: 'AzureResumeConnection'
          scriptType: powershell  # Switch back to PowerShell
          scriptLocation: inlineScript
          inlineScript: |
            az logout
