trigger:
  branches:
    include:
      - main        # Specify the branch you want to trigger the pipeline from (e.g., main)
  paths:
    include:
      - 'infrastructure/**'  # Trigger on any changes under the infrastructure folder

pr:
  branches:
    include:
      - main        # Specify the branch you want to trigger the PR validation from (e.g., main)
  paths:
    include:
      - 'infrastructure/**'  # Trigger on any changes under the infrastructure folder

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_RESOURCE_GROUP: 'azure-cloud-resume-rg'  # Set this to your resource group name

jobs:
- job: DeployInfrastructure
  displayName: 'Deploy Infrastructure'
  steps:

    
    # Log in to Azure using Service Principal
    - task: AzureCLI@2
      displayName: 'Azure Login'
      inputs:
        azureSubscription: 'AzureResumeConnection'  # Name of the service connection you created
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
    
    # Deploy Bicep file using Azure CLI
    - task: AzureCLI@2
      displayName: 'Deploy Bicep Template'
      inputs:
        azureSubscription: 'MyAzureConnection'  # Name of the service connection you created
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az deployment group create \
            --resource-group $(AZURE_RESOURCE_GROUP) \
            --template-file ./infrastructure/main.bicep \
            --parameters ./infrastructure/parameters.bicepparam
    
    # Logout from Azure
    - task: AzureCLI@2
      displayName: 'Azure Logout'
      inputs:
        azureSubscription: 'MyAzureConnection'  # Name of the service connection you created
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az logout
