name: Deploy_frontend

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
  AZURE_BLOB_STORAGE_ACCOUNT_NAME: 'stgwebazurecloudresumeik'   # set this to your blob storage account name that hosts static website
  AZURE_CDN_PROFILE_NAME: 'azurecloudresumeik7k'       # set this to your cdn profile name
  AZURE_CDN_ENDPOINT_NAME: 'azurecloudresumeik7k'                   # set this to your cdn endpoint name
  AZURE_RESOURCE_GROUP: 'azure-cloud-resume-rg'                   # set this to your resource group name

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ env.AZURE_BLOB_STORAGE_ACCOUNT_NAME }} --auth-mode key -d '$web' -s frontend/ --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name ${{ env.AZURE_CDN_PROFILE_NAME }} --name ${{ env.AZURE_CDN_ENDPOINT_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()