name: Deploy_infrastructure

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
  AZURE_RESOURCE_GROUP: 'azure-cloud-resume-rg'                   # set this to your resource group name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ AZURE_RESOURCE_GROUP }}
        template: ./infrastructure/main.bicep
        parameters: ./infrastructure/parameters.bicepparam
        failOnStdErr: false

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()